/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

typedef ... SignalOpaque_f64_t;

SignalOpaque_f64_t *
sig (void);

SignalOpaque_f64_t *
sig_cos (
    double omega,
    double theta);

double
sig_sample (
    SignalOpaque_f64_t * s,
    int32_t n);

SignalOpaque_f64_t *
sig_unit (void);

typedef ... StateFullMachineOpaque_SensorInput_Action_t;

bool
sm_is_done (
    StateFullMachineOpaque_SensorInput_Action_t * sm);

void
sm_reset (
    StateFullMachineOpaque_SensorInput_Action_t * sm);

StateFullMachineOpaque_SensorInput_Action_t *
sm_simple (
    double _incr);

typedef struct {
    double idx[8];
} double_8_array_t;

typedef struct Point {
    double x;

    double y;
} Point_t;

typedef struct Pose {
    Point_t pos;

    double theta;
} Pose_t;

typedef struct SensorInput {
    double_8_array_t sonars;

    Pose_t odometry;
} SensorInput_t;

typedef struct Action {
    double fvel;

    double rvel;
} Action_t;

Action_t
sm_step (
    StateFullMachineOpaque_SensorInput_Action_t * sm,
    SensorInput_t input);

