/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

typedef ... StateFullMachineOpaque_SensorInput_Action_t;

bool
sm_is_done (
    StateFullMachineOpaque_SensorInput_Action_t * sm);

void
sm_reset (
    StateFullMachineOpaque_SensorInput_Action_t * sm);

typedef struct Action {
    double fvel;

    double rvel;
} Action_t;

typedef struct Vec_Action {
    Action_t * ptr;

    size_t len;

    size_t cap;
} Vec_Action_t;

Vec_Action_t
sm_run (
    StateFullMachineOpaque_SensorInput_Action_t * sm,
    size_t n);

StateFullMachineOpaque_SensorInput_Action_t *
sm_simple (
    double incr);

typedef struct {
    double idx[8];
} double_8_array_t;

typedef struct Position {
    double x;

    double y;
} Position_t;

typedef struct Pose {
    Position_t pos;

    double theta;
} Pose_t;

typedef struct SensorInput {
    double_8_array_t sonars;

    Pose_t odometry;
} SensorInput_t;

Action_t
sm_step (
    StateFullMachineOpaque_SensorInput_Action_t * sm,
    SensorInput_t input);

