/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

typedef ... StateFullMachineOpaque_t;

StateFullMachineOpaque_t *
sm_new (void);

void
sm_reset (
    StateFullMachineOpaque_t * sm);

int32_t
sm_step (
    StateFullMachineOpaque_t * sm,
    int32_t input);

