/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

typedef ... StateFullMachineOpaque_f64_f64_t;

StateFullMachineOpaque_f64_f64_t *
sm_counter (void);

StateFullMachineOpaque_f64_f64_t *
sm_factorial (void);

void
sm_reset (
    StateFullMachineOpaque_f64_f64_t * sm);

typedef struct Vec_double {
    double * ptr;

    size_t len;

    size_t cap;
} Vec_double_t;

Vec_double_t
sm_run (
    StateFullMachineOpaque_f64_f64_t * sm,
    size_t n);

double
sm_step (
    StateFullMachineOpaque_f64_f64_t * sm,
    double input);

StateFullMachineOpaque_f64_f64_t *
sm_world (void);

