/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

typedef ... SignalOpaque_f64_t;

SignalOpaque_f64_t *
sig (
    double k3,
    double k4,
    double desired_d);

SignalOpaque_f64_t *
sig_cos (
    double omega,
    double theta);

double
sig_sample (
    SignalOpaque_f64_t * s,
    int32_t n);

SignalOpaque_f64_t *
sig_unit (void);

typedef ... StateFullMachineOpaque_AnglePropInput_Action_t;

StateFullMachineOpaque_AnglePropInput_Action_t *
sm (
    double desired_d,
    double k1,
    double k2);

bool
sm_is_done (
    StateFullMachineOpaque_AnglePropInput_Action_t * sm);

void
sm_reset (
    StateFullMachineOpaque_AnglePropInput_Action_t * sm);

typedef struct Tuple2_bool_double {
    bool _0;

    double _1;
} Tuple2_bool_double_t;

typedef struct AnglePropInput {
    double distance;

    Tuple2_bool_double_t angle;
} AnglePropInput_t;

typedef struct Action {
    double fvel;

    double rvel;
} Action_t;

Action_t
sm_step (
    StateFullMachineOpaque_AnglePropInput_Action_t * sm,
    AnglePropInput_t input);

